a = int(input("Enter first number: "))
b = int(input("Enter second number: "))

print("Addition =", a + b)
print("Subtraction =", a - b)
print("Multiplication =", a * b)
print("Division =", a / b)
print("Remainder =", a % b)
print("Floor Division =", a // b)
print("Power =", a ** b)
